<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-08-08T16:36:36Z" name="Default suite" finished-at="2019-08-08T16:38:32Z" duration-ms="116099">
    <groups>
    </groups>
    <test started-at="2019-08-08T16:36:36Z" name="Default test" finished-at="2019-08-08T16:38:32Z" duration-ms="116099">
      <class name="com.testcases.qa.logintestcase">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:36:36Z" name="setup" finished-at="2019-08-08T11:37:02Z" duration-ms="25944" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="logintestcase(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:37:02Z" name="logintestcase" data-provider="amazonlogindata" finished-at="2019-08-08T11:37:05Z" duration-ms="3370" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[9606188565]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[9606188565]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Provided invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Provided invalid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.pages.qa.loginpages.loginp(loginpages.java:40)
	at com.testcases.qa.logintestcase.logintestcase(logintestcase.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintestcase -->
        <test-method is-config="true" signature="screenShot(org.testng.ITestResult)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:37:05Z" name="screenShot" finished-at="2019-08-08T11:37:07Z" duration-ms="1924" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logintestcase status=FAILURE method=logintestcase.logintestcase(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenShot -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:37:07Z" name="setup" finished-at="2019-08-08T11:37:32Z" duration-ms="24759" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="logintestcase(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:37:32Z" name="logintestcase" data-provider="amazonlogindata" finished-at="2019-08-08T11:37:34Z" duration-ms="1948" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[9606188565@]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[9606188565]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Provided invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Provided invalid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.pages.qa.loginpages.loginp(loginpages.java:40)
	at com.testcases.qa.logintestcase.logintestcase(logintestcase.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintestcase -->
        <test-method is-config="true" signature="screenShot(org.testng.ITestResult)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:37:34Z" name="screenShot" finished-at="2019-08-08T11:37:35Z" duration-ms="1533" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logintestcase status=FAILURE method=logintestcase.logintestcase(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenShot -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:37:35Z" name="setup" finished-at="2019-08-08T11:38:01Z" duration-ms="25452" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="logintestcase(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:38:01Z" name="logintestcase" data-provider="amazonlogindata" finished-at="2019-08-08T11:38:03Z" duration-ms="2320" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[9606188565]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[96061885-5]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Provided invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Provided invalid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.pages.qa.loginpages.loginp(loginpages.java:40)
	at com.testcases.qa.logintestcase.logintestcase(logintestcase.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintestcase -->
        <test-method is-config="true" signature="screenShot(org.testng.ITestResult)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:38:03Z" name="screenShot" finished-at="2019-08-08T11:38:04Z" duration-ms="1471" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logintestcase status=FAILURE method=logintestcase.logintestcase(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenShot -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:38:04Z" name="setup" finished-at="2019-08-08T11:38:31Z" duration-ms="26236" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify()[pri:2, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:38:31Z" name="verify" finished-at="2019-08-08T11:38:31Z" duration-ms="26" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
        <test-method is-config="true" signature="screenShot(org.testng.ITestResult)[pri:0, instance:com.testcases.qa.logintestcase@55a561cf]" started-at="2019-08-08T11:38:31Z" name="screenShot" finished-at="2019-08-08T11:38:32Z" duration-ms="1074" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify status=SUCCESS method=logintestcase.verify()[pri:2, instance:com.testcases.qa.logintestcase@55a561cf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenShot -->
      </class> <!-- com.testcases.qa.logintestcase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
