<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-08-07T06:17:30Z" name="Default suite" finished-at="2019-08-07T06:18:30Z" duration-ms="59264">
    <groups>
    </groups>
    <test started-at="2019-08-07T06:17:30Z" name="Default test" finished-at="2019-08-07T06:18:30Z" duration-ms="59264">
      <class name="com.testcases.qa.logintestcase">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.testcases.qa.logintestcase@2893de87]" started-at="2019-08-07T01:17:30Z" name="setup" finished-at="2019-08-07T01:17:58Z" duration-ms="27206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="logintestcase()[pri:1, instance:com.testcases.qa.logintestcase@2893de87]" started-at="2019-08-07T01:17:58Z" name="logintestcase" finished-at="2019-08-07T01:18:00Z" duration-ms="2766" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintestcase -->
        <test-method is-config="true" signature="screenShot(org.testng.ITestResult)[pri:0, instance:com.testcases.qa.logintestcase@2893de87]" started-at="2019-08-07T01:18:00Z" name="screenShot" finished-at="2019-08-07T01:18:02Z" duration-ms="1733" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logintestcase status=SUCCESS method=logintestcase.logintestcase()[pri:1, instance:com.testcases.qa.logintestcase@2893de87] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenShot -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.testcases.qa.logintestcase@2893de87]" started-at="2019-08-07T01:18:02Z" name="setup" finished-at="2019-08-07T01:18:28Z" duration-ms="25681" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify()[pri:2, instance:com.testcases.qa.logintestcase@2893de87]" started-at="2019-08-07T01:18:28Z" name="verify" finished-at="2019-08-07T01:18:28Z" duration-ms="83" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Amazon Sign-I] but found [Amazon Sign-In]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Amazon Sign-I] but found [Amazon Sign-In]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.testcases.qa.logintestcase.verify(logintestcase.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
        <test-method is-config="true" signature="screenShot(org.testng.ITestResult)[pri:0, instance:com.testcases.qa.logintestcase@2893de87]" started-at="2019-08-07T01:18:28Z" name="screenShot" finished-at="2019-08-07T01:18:30Z" duration-ms="1764" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify status=FAILURE method=logintestcase.verify()[pri:2, instance:com.testcases.qa.logintestcase@2893de87] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenShot -->
      </class> <!-- com.testcases.qa.logintestcase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
